main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),

    # Routes for Classrooms
    path('classrooms/', views.classrooms_index, name='classrooms_index'),
    path('classrooms/<int:classroom_id>/', views.classrooms_detail, name='classrooms_detail'),
    path('classrooms/create/', views.ClassroomCreate.as_view(), name='classrooms_create'),
    path('classrooms/<int:pk>/update/', views.ClassroomUpdate.as_view(), name='classrooms_update'),
    path('classrooms/<int:pk>/delete/', views.ClassroomDelete.as_view(), name='classrooms_delete'),
    # Routes for Students
    path('students/', views.students_index, name='students_index'),
    path('students/<int:student_id>/', views.students_detail, name='students_detail'),
    path('students/create/', views.StudentsCreate.as_view(), name='students_create'),
    path('students/<int:pk>/update/', views.StudentsUpdate.as_view(), name='students_update'),
    path('students/<int:pk>/delete/', views.StudentsDelete.as_view(), name='students_delete'),
    path('students/<int:student_id>/add_photo', views.add_photo, name='add_photo'),
    # Routes for Assignments
    path('assignments/', views.assignments_index, name='assignments_index'),
    path('assignments/<int:assignment_id>/', views.assignments_detail, name='assignments_detail'),
    path('assignments/create/', views.AssignmentCreate.as_view(), name='assignments_create'),
    path('assignments/<int:pk>/update', views.AssignmentUpdate.as_view(), name='assignments_update'),
    path('assignments/<int:pk>/delete', views.AssignmentDelete.as_view(), name='assignments_delete'),
    # Routes for User Auth
    path('accounts/signup/', views.signup, name='signup'), 

    # Associate assignments to classroom 
    path('classrooms/<int:classroom_id>/assoc_assignment/<int:assignment_id>/', views.assoc_assignment_to_classroom, name='assoc_assignment'),
    # Unassociate assignments to classroom 
    path('classrooms/<int:classroom_id>/unassoc_assignment/<int:assignment_id>/', views.unassoc_assignment_to_classroom, name='unassoc_assignment'),
    
    path('classrooms/<int:classroom_id>/assoc_student/<int:student_id>/', views.assoc_student_to_classroom, name='assoc_student'),
    path('classrooms/<int:classroom_id>/unassoc_student/<int:student_id>/', views.unassoc_student_to_classroom, name='unassoc_student'),
    
    # Router for Dashboard
    path('dashboard/', views.dashboard, name='dashboard'), 
    
]

onedge/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.urls import reverse
from django.contrib.auth.models import User

# Student model 
class Student(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    age = models.IntegerField()

    def __str__(self):
        return self.first_name

class Assignment(models.Model):
    description = models.TextField(max_length=1000)
    due_date = models.DateField()
    # completed_date = models.DateField(null=True) 
    user = models.ForeignKey(User, on_delete=CASCADE)

    def __str__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('assignments_detail', kwargs={'pk': self.id})

class Classroom(models.Model):
    course_subject = models.CharField(max_length=100)
    course_number = models.IntegerField()
    course_name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=CASCADE)
    assignments = models.ManyToManyField(Assignment)
    students = models.ManyToManyField(Student)
    
    def __str__(self):
        return f'{self.course_subject} {self.course_number}, {self.course_name}'

    def get_absolute_url(self):
        return reverse('classrooms_detail', kwargs={'pk': self.id})

class Profile(models.Model):
  is_teacher = models.BooleanField()
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  first_name = models.CharField(max_length=100, default=None)
  last_name = models.CharField(max_length=100, default=None)
  email = models.EmailField(default=None)

class Photo(models.Model):
    url = models.CharField(max_length=200)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for student_id: {self.student_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Profile

class ProfileForm(ModelForm):
  class Meta:
    model = Profile
    fields = ['is_teacher', 'first_name', 'last_name', 'email']
    labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'email': 'Email Address',
            'is_teacher': ''
    }

main_app/views.py
from django.shortcuts import render, redirect
from .models import Assignment, Classroom, Student, Photo
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ProfileForm

import boto3
import uuid

S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'onedge'

# Create your views here.
def home(req):
    return render(req, 'home.html')

def about(req):
    return render(req, 'about.html')

@login_required  
def assignments_index(req):
    assignments = Assignment.objects.filter(user=req.user)
    return render(req, 'assignments/index.html', {
        'assignments': assignments,
        'profile': req.user.profile   
    })

@login_required  
def assignments_detail(req, assignment_id):
    assignment = Assignment.objects.get(id=assignment_id)
    return render(req, 'assignments/detail.html', {'assignment': assignment})
    
class AssignmentCreate(LoginRequiredMixin, CreateView):
    model = Assignment
    fields = ['description', 'due_date']
    success_url = '/assignments/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
        
class AssignmentUpdate(LoginRequiredMixin, UpdateView):
    model = Assignment
    fields = ['description', 'due_date']
    success_url = '/assignments/'

class AssignmentDelete(LoginRequiredMixin,DeleteView):
    model = Assignment
    success_url = '/assignments/'

@login_required  
def classrooms_index(req):
    classrooms = Classroom.objects.filter(user=req.user)
    return render(req, 'classrooms/index.html', {
        'classrooms': classrooms,
         'profile': req.user.profile   
        })

@login_required  
def classrooms_detail(req, classroom_id):
    classroom = Classroom.objects.get(id=classroom_id)
    assignments = Assignment.objects.filter(user=req.user)
    students = Student.objects.all()
    unassigned_assignments = assignments.exclude(id__in = classroom.assignments.all().values_list('id'))
    unassigned_students = students.exclude(id__in = classroom.students.all().values_list('id'))
    return render(req, 'classrooms/detail.html', {
        'classroom': classroom,
        'allAssignments': assignments,
        'unassigned': unassigned_assignments,
        'all_students': students,
        'unassigned_students': unassigned_students
    })

@login_required
def assoc_assignment_to_classroom(req, classroom_id, assignment_id):
    Classroom.objects.get(id=classroom_id).assignments.add(assignment_id)
    return redirect('classrooms_detail', classroom_id=classroom_id)

@login_required
def unassoc_assignment_to_classroom(req, classroom_id, assignment_id):
    Classroom.objects.get(id=classroom_id).assignments.remove(assignment_id)
    return redirect('classrooms_detail', classroom_id=classroom_id)

class ClassroomCreate(LoginRequiredMixin, CreateView):
    model = Classroom
    fields = ['course_subject', 'course_number', 'course_name']
    success_url = '/classrooms/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class ClassroomUpdate(LoginRequiredMixin, UpdateView):
    model = Classroom
    fields = ['course_subject', 'course_number', 'course_name']
    success_url = '/classrooms/'

class ClassroomDelete(LoginRequiredMixin, DeleteView):
    model = Classroom
    success_url = '/classrooms/'


def signup(request):
    error_message = ''
    if request.method == 'POST':
        user_form = UserCreationForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            login(request, user)
            return redirect('classrooms_index')
        else:
            error_message = 'Invalid Signup Data - Please Try Again'
    #create user
    user_form = UserCreationForm()
    profile_form = ProfileForm()

    return render(request, 'registration/signup.html', {
        'user_form': user_form, 
        'error_message': error_message,
        'profile_form': profile_form 
    })
    # return render(request, 'registration/signup.html', context)
  
@login_required  
def students_index(req):
    students = Student.objects.all()
    return render(req, 'students/index.html', {'students': students})

@login_required
def students_detail(req, student_id):
    student = Student.objects.get(id=student_id)
    return render(req, 'students/detail.html', {'student': student})

class StudentsCreate(LoginRequiredMixin, CreateView):
    model = Student
    fields = '__all__'
    success_url = '/students/'

class StudentsUpdate(LoginRequiredMixin, UpdateView):
    model = Student
    fields = '__all__'
    success_url = '/students/'

class StudentsDelete(LoginRequiredMixin, DeleteView):
    model = Student
    success_url = '/students/'
    user_form = UserCreationForm()
    profile_form = ProfileForm()
    context = {
    'user_form': user_form, 
    'profile_form': profile_form
  }

@login_required
def assoc_student_to_classroom(req, classroom_id, student_id):
    Classroom.objects.get(id=classroom_id).students.add(student_id)
    return redirect('classrooms_detail', classroom_id=classroom_id)

@login_required
def unassoc_student_to_classroom(req, classroom_id, student_id):
    Classroom.objects.get(id=classroom_id).students.remove(student_id)
    return redirect('classrooms_detail', classroom_id=classroom_id)

@login_required
def dashboard(req):
  user_type = None
  assignments = Assignment.objects.filter(user=req.user)
  classrooms = Classroom.objects.filter(user=req.user)

  if req.user.profile.is_teacher:
    user_type = 'teacher'
  else:
    user_type = 'student'
  return render(req, f'{user_type}_dashboard.html', {
        'assignments': assignments,
        'classrooms': classrooms,
        'user': req.user,
        'profile': req.user.profile
    })

def add_photo(request, student_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, student_id=student_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('students_detail', student_id=student_id)

main_app/templates/main_app/assignment_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1 class="nav-header">Delete Assignment {{ object.id }}</h1>


<style>
    body {
      background-image: url('https://img.wallpapersafari.com/desktop/1680/1050/34/41/vj3iml.jpg');
      background-repeat: no-repeat;
      background-size: 100% 100%; 
    }
</style>
<div class="deleteContainer">
    <div class="card">
        <div class="card-content">
            <h4 id="message">Are you sure you want to delete Assignment {{ object.id }}?</h4>
            <hr size="8" width="100%" color="rgb(66, 14, 114)">
            <br>
            <form action="" method="POST">
                {% csrf_token %}
                <input type="submit" value="✔" class="btn-floating icons">
                <a href="{% url 'assignments_detail' assignment.id %}">
                    <input type="submit" value="✘" class="btn-floating icons">
                </a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/assignment_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Assignment Detail</h1>
<div class="card">
    <div class="card-content">
      <span class="card-title">Assignment Number {{ object.id }}</span>
      <p><span class="heading">Description:</span> {{ assignment.description }}</p>
      <p><span class="heading">Due Date:</span> {{ assignment.due_date }}</p>
    </div>
    <div class="card-action">
        <a class="btn-floating pulse" href="{% url 'assignments_update' assignment.id %}"><i class="material-icons"> edit</i></a>
        <a class="btn-floating pulse" href="{% url 'assignments_delete' assignment.id %}"><i class="material-icons"> delete</i></a>
    </div>
</div>
{% endblock %}

main_app/templates/main_app/assignment_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<h1 class="nav-header">Edit Assignment {{ object.id }}</h1>
{% else %}
<h1 class="nav-header">Add New Assignment</h1>
{% endif %}
<style>
    body {
      background-image: url('https://img.wallpapersafari.com/desktop/1680/1050/34/41/vj3iml.jpg');
      background-repeat: no-repeat;
      background-size: 100% 100%; 
    }
</style>
<div id="assCreateContainer">
    <div class="card">
        <div class="card-content">
            <form action="" method="POST">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <br>
                <input type="submit" value='✔︎' class="btn-floating icons">
            </form>
        </div>
    </div>
</div>
<script>
    const dueDateEl = document.querySelector('#id_due_date');
    M.Datepicker.init(dueDateEl, {
        format: 'yyyy-mm-dd',
        // defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    })
</script>
{% endblock %}

main_app/templates/main_app/assignment_list.html
{% extends 'base.html' %}

{% block content %}
<h1 id="assigment">Current Assignments</h1>



{% for assignment in assignment_list %}
<a href="{% url 'assignments_detail' assignment.id %}">
    <div class="card" id="card">
        <div class="card-content">
            <span class="card-title">Assignment number {{ assignment.id }}</span>
            <p><span class="heading">Description:</span> {{ assignment.description }}</p>
            <p><span class="heading">Due Date:</span> {{ assignment.due_date }}</p>
        </div>
    </div>
</a>

{% endfor %}
<a id="add" href="{% url 'assignments_create' %}"><i class="material-icons"> add</i>Create an Assignment</a>


<style>
    body {
      background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8eYyAr3CAH6jI0MGAnwa2El8oLZURFCzu9A&usqp=CAU')
    }
    #assigment{
        text-align: center;
        font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
        color: rgb(151, 76, 68);
    }
    #card{
        font-family: fantasy;
        color:slategray;
    }

    #add {
        color: rgb(122, 42, 10);
        font-weight: bold;
        font-family: monospace;
    }
    </style>


{% endblock %}

main_app/templates/main_app/classroom_confirm_delete.html
{% extends 'base.html' %}

{% block content%}

<h1 class="nav-header">Delete Classroom</h1>

<style>
    body {
        background-image: url('https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1934&q=80');
      background-repeat: no-repeat;
      background-size: 100% 100%; 
    }
</style>
<div class="deleteContainer">
    <div class="card">
        <div class="card-content">
            <h4>Are you sure you want to delete {{ object.course_subject }} {{ object.course_number }}?</h4>
            <hr size="8" width="100%" color="rgb(66, 14, 114)">
            <br>
            <form action="" method="POST">
                {% csrf_token %}
                <input class="btn-floating icons" type="submit" value="✔︎">
                <a href="{% url 'classrooms_detail' classroom.id %}">
                    <input type="submit" value="✘" class="btn-floating icons">
                </a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/classroom_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1 class="nav-header">Edit {{ object.course_subject }}{{ object.course_number }}</h1>
{% else %}
    <h1 class="nav-header">Add A New Classroom</h1>
{% endif %}
<style>
    body {
        background-image: url('https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1934&q=80');
        background-repeat: no-repeat;
        background-size: 100% 100%; 
    }
</style>

<div id="classCreateContainer">
    <div class="card">
        <div class="card-content">
            <form action="" method="POST">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <br>
                <input type="submit" value='✔︎' class="btn-floating icons">
            </form>
        </div>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/student_confirm_delete.html
{% extends 'base.html' %}

{% block content%}

<h1 class="nav-header">Delete Student</h1>

<style>
    body {
        background-image: url('https://cdn.wallpapersafari.com/78/70/XIbUE1.jpg');
      background-repeat: no-repeat;
      background-size: 100% 100%;   
    }
</style>



<div class="deleteContainer">
    <div class="card">
        <div class="card-content">
            <h4 id="message">Are you sure you want to delete student:  {{ object.first_name }} {{ object.last_name }}?</h4>
            <hr size="8" width="100%" color="rgb(66, 14, 114)">
            <br>
            <form action="" method="POST">
                {% csrf_token %}
                <input class="btn-floating icons" type="submit" value="✔︎">
                <input class="btn-floating icons" type="submit" value="✘" href="">
            </form>
        </div>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/student_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1 class="nav-header">Edit {{ object.first_name }} {{ object.last_name }}</h1>
{% else %}
    <h1 class="nav-header">Add A New Student</h1>
{% endif %}

<div id="studentContainer">
    <div class="card">
        <div class="card-content">
            <form action="" method="POST">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <br>
                <input class="btn-floating icons" type="Submit" value="✔︎">
            </form>
        </div>
    </div>
</div>

<style>
    body {
        background-image: url('https://cdn.wallpapersafari.com/78/70/XIbUE1.jpg');
      background-repeat: no-repeat;
      background-size: 100% 100%;   
    }
</style>

{% endblock %}